# Generated by Django 2.0.2 on 2018-12-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20181206_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('is_teacher', 'Is Teacher'), ('is_student', 'Is Student'))},
        ),
    ]
